version: '3.4'

networks:
  geolocalizacionips-dev:
    driver: bridge 

services:
  angular-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: angular-ui
    volumes:
        - ./frontend:/app/frontend
        - /app/frontend/node_modules

  geolocalizacionips:
    image: geolocalizacionips:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=GeolocalizacionIPs;username=geolocuser;password=geolocuser"
    networks:
      - geolocalizacionips-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./database/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "geolocuser"
      POSTGRES_PASSWORD: "geolocuser"
      POSTGRES_DB: "GeolocalizacionIPs"
    networks:
      - geolocalizacionips-dev
volumes:
  db_volume: