\connect GeolocalizacionIPs

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "IPInfos" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Pais" text NULL,
    "CodigoISOPais" text NULL,
    "FranjasHorarias" text NULL,
    "Idiomas" text NULL,
    "DistanciaABuenosAires" double precision NOT NULL,
    "Moneda" text NULL,
    "Invocaciones" bigint NOT NULL,
    CONSTRAINT "PK_IPInfos" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210519002521_initial', '5.0.6');

COMMIT;