// <auto-generated />
using GeolocalizacionIPs.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GeolocalizacionIPs.Migrations
{
    [DbContext(typeof(GeolocalizacionIPsContext))]
    [Migration("20210519002521_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GeolocalizacionIPs.Entities.IPInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodigoISOPais")
                        .HasColumnType("text");

                    b.Property<double>("DistanciaABuenosAires")
                        .HasColumnType("double precision");

                    b.Property<string>("FranjasHorarias")
                        .HasColumnType("text");

                    b.Property<string>("Idiomas")
                        .HasColumnType("text");

                    b.Property<long>("Invocaciones")
                        .HasColumnType("bigint");

                    b.Property<string>("Moneda")
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IPInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
